### PR TITLE
Fix #47. Sort paths and components for deterministic specification

### LINKED ISSUE #47: The generation-result is not deterministic
**Describe the bug**
I have a controller-class.
I'm able to generate json and yaml.
But every time I run the plugin the result looks different to the prev. one.
This is not so helpfull because I put the result into my git-repo.

```
<plugin>
        <groupId>io.swagger.core.v3</groupId>
        <artifactId>swagger-maven-plugin</artifactId>
        <version>${swagger-maven-plugin.version}</version>
        <configuration>
          <outputPath>${basedir}/src/openapi/</outputPath>
          <outputFileName>cc-${api.version}</outputFileName>
          <outputFormat>JSONANDYAML</outputFormat>
          <prettyPrint>TRUE</prettyPrint>
          <attachSwaggerArtifact>true</attachSwaggerArtifact>
          <resourceClasses>
            <resourceClasse>com.siemens.spice.cc.rest.service.ConfigurationController</resourceClasse>
          </resourceClasses>
        </configuration>
        <executions>
          <execution>
            <phase>compile</phase>
            <goals>
              <goal>resolve</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

**To Reproduce**
Simply run the generation multiple time without any change.

**Expected behavior**
The generated json/yaml must create always the same output.

I tried to "fix" this behavior in io.openapitools.swagger.GenerateMojo.execute()

```java
OpenAPI swagger = reader.read(reflectiveScanner.classes());

// XXX .... try to bring all the props in a "stable" order ...
swagger.paths(sortPaths(swagger.getPaths()));
swagger.components(sortComponents(swagger.getComponents()));

```
...
```java
private Components sortComponents(Components components) {
        if (components==null)
            return null;
        Components r = new Components();
        r.setSchemas(sort(components.getSchemas()));
        return r;
    }

    private io.swagger.v3.oas.models.Paths sortPaths(io.swagger.v3.oas.models.Paths paths) {
        if (paths==null)
            return null;
        io.swagger.v3.oas.models.Paths r = new io.swagger.v3.oas.models.Paths();
        r.putAll(sort(paths));
        return r;
    }

    private <K extends Comparable<K>, V> Map<K, V> sort(Map<K, V> map) {
        return map
                .entrySet()
                .stream()
                .sorted(Map.Entry.comparingByKey())
                .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
    }
``´


But I'm not sure if this is the right direction to go :)

### PR DESCRIPTION
**Pull request by hiddewie**
### Problem

There is non-deterministic output of the generation of the OpenAPI 3.0 document produced by this plugin. Also see #47.

When the file is committed to a source code repository, this causes a diff without changing the actual content of the specification.

The sorting is done by a specialized class, which may be removed after this has been fixed in `swagger-core`.

### This PR

- Add sorting of:
  - `paths`
  - `components`:
    - `Schemas` (recursively)
    - `Responses`
    - `Parameters`
    - `Examples`
    - `RequestBodies`
    - `Headers`
    - `SecuritySchemes`
    - `Links`
    - `Callbacks`
    - `Extensions`
- Improve tests by adding strict file contents equality for existing fixtures. Some of the fixtures in the source code were actually not waht the plugin generated (the OpenAPI content was equal, but the file contents were not).

This should solve the problem.

### References to other issues and pull requests in Swagger Core:

- https://github.com/swagger-api/swagger-core/issues/3475
- https://github.com/swagger-api/swagger-core/pull/3476
- swagger-api/swagger-core#2775
- swagger-api/swagger-core#2828
- swagger-api/swagger-core#3266
- swagger-api/swagger-core#2400

### CODE REVIEW

**Comment by langecode** [comment]
Great, thx. I will take a look today or tonight and possibly make a new release including this feature.

**Comment by hiddewie** [comment]
We found another non-deterministic issue with the order of the properties of a Schema (`/components/schemas/*/properties`). We will also push a fix for that as well on this branch.

All the sorting logic will be extracted to a separate class for better separation of concerns.

**Comment by hiddewie** [comment]
I also created https://github.com/swagger-api/swagger-core/pull/3613 which solves exactly this problem in Swagger Core, without the code in this PR.

**Comment by hiddewie** [comment]
Thank you @langecode for the very quick response!

**Comment by langecode** [comment]
You're welcome. I did change the implementation a little bit but should have the same sematics :)

**Pull request merged**
